# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testmycontacts

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_688556ad11254b30ab5204b37c277fe1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1a936004b37b476bab1fa92f0d55c684 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_688556ad11254b30ab5204b37c277fe1 }}/doijodeakash/mycontacts:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testmycontacts'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8ff1c29e9d3d4951b047541a77b248bc }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_688556ad11254b30ab5204b37c277fe1 }}/doijodeakash/mycontacts:${{ github.sha }}'